package jisx4061

var table = map[rune]attr{
	// スペース
	'　': {
		class: classSpace,
		order: 1,
	},
	' ': {
		class: classSpace,
		order: 1,
	},

	// 記述記号
	'、': {
		class: classDescriptor,
		order: 1,
	},
	'。': {
		class: classDescriptor,
		order: 2,
	},
	'，': {
		class: classDescriptor,
		order: 3,
	},
	'．': {
		class: classDescriptor,
		order: 4,
	},
	'・': {
		class: classDescriptor,
		order: 5,
	},
	'：': {
		class: classDescriptor,
		order: 6,
	},
	'；': {
		class: classDescriptor,
		order: 7,
	},
	'？': {
		class: classDescriptor,
		order: 8,
	},
	'！': {
		class: classDescriptor,
		order: 9,
	},
	'￣': {
		class: classDescriptor,
		order: 10,
	},
	'＿': {
		class: classDescriptor,
		order: 11,
	},
	'―': { // HORIZONTAL BAR
		class: classDescriptor,
		order: 12,
	},
	'‐': { // HYPHEN
		class: classDescriptor,
		order: 13,
	},
	'／': {
		class: classDescriptor,
		order: 14,
	},
	'＼': {
		class: classDescriptor,
		order: 15,
	},
	'～': {
		class: classDescriptor,
		order: 16,
	},
	'∥': {
		class: classDescriptor,
		order: 17,
	},
	'｜': {
		class: classDescriptor,
		order: 18,
	},
	'…': {
		class: classDescriptor,
		order: 19,
	},
	'‥': {
		class: classDescriptor,
		order: 20,
	},

	// 括弧記号
	'‘': {
		class: classBracket,
		order: 1,
	},
	'’': {
		class: classBracket,
		order: 1,
	},
	'“': {
		class: classBracket,
		order: 1,
	},
	'”': {
		class: classBracket,
		order: 1,
	},
	'（': {
		class: classBracket,
		order: 1,
	},
	'）': {
		class: classBracket,
		order: 1,
	},
	'〔': {
		class: classBracket,
		order: 1,
	},
	'〕': {
		class: classBracket,
		order: 1,
	},
	'［': {
		class: classBracket,
		order: 1,
	},
	'］': {
		class: classBracket,
		order: 1,
	},
	'｛': {
		class: classBracket,
		order: 1,
	},
	'｝': {
		class: classBracket,
		order: 1,
	},
	'〈': {
		class: classBracket,
		order: 1,
	},
	'〉': {
		class: classBracket,
		order: 1,
	},
	'《': {
		class: classBracket,
		order: 1,
	},
	'》': {
		class: classBracket,
		order: 1,
	},
	'「': {
		class: classBracket,
		order: 1,
	},
	'」': {
		class: classBracket,
		order: 1,
	},
	'『': {
		class: classBracket,
		order: 1,
	},
	'』': {
		class: classBracket,
		order: 1,
	},
	'【': {
		class: classBracket,
		order: 1,
	},
	'】': {
		class: classBracket,
		order: 1,
	},

	// TODO: 学術記号

	// TODO: 一般記号

	// TODO: 単位記号

	// アラビア数字
	'０': {
		class: classNumber,
		order: 1,
	},
	'１': {
		class: classNumber,
		order: 2,
	},
	'２': {
		class: classNumber,
		order: 3,
	},
	'３': {
		class: classNumber,
		order: 4,
	},
	'４': {
		class: classNumber,
		order: 5,
	},
	'５': {
		class: classNumber,
		order: 6,
	},
	'６': {
		class: classNumber,
		order: 7,
	},
	'７': {
		class: classNumber,
		order: 8,
	},
	'８': {
		class: classNumber,
		order: 9,
	},
	'９': {
		class: classNumber,
		order: 10,
	},

	'0': {
		class: classNumber,
		order: 1,
	},
	'1': {
		class: classNumber,
		order: 2,
	},
	'2': {
		class: classNumber,
		order: 3,
	},
	'3': {
		class: classNumber,
		order: 4,
	},
	'4': {
		class: classNumber,
		order: 5,
	},
	'5': {
		class: classNumber,
		order: 6,
	},
	'6': {
		class: classNumber,
		order: 7,
	},
	'7': {
		class: classNumber,
		order: 8,
	},
	'8': {
		class: classNumber,
		order: 9,
	},
	'9': {
		class: classNumber,
		order: 10,
	},

	// TODO: 欧字記号

	// ラテンアルファベット
	'ａ': {
		class:           classAlphabet,
		order:           1,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'ｂ': {
		class:           classAlphabet,
		order:           2,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'ｃ': {
		class:           classAlphabet,
		order:           3,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'ｄ': {
		class:           classAlphabet,
		order:           4,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'ｅ': {
		class:           classAlphabet,
		order:           5,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'ｆ': {
		class:           classAlphabet,
		order:           6,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'ｇ': {
		class:           classAlphabet,
		order:           7,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'ｈ': {
		class:           classAlphabet,
		order:           8,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'ｉ': {
		class:           classAlphabet,
		order:           9,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'ｊ': {
		class:           classAlphabet,
		order:           10,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'ｋ': {
		class:           classAlphabet,
		order:           11,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'ｌ': {
		class:           classAlphabet,
		order:           12,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'ｍ': {
		class:           classAlphabet,
		order:           13,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'ｎ': {
		class:           classAlphabet,
		order:           14,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'ｏ': {
		class:           classAlphabet,
		order:           15,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'ｐ': {
		class:           classAlphabet,
		order:           16,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'ｑ': {
		class:           classAlphabet,
		order:           17,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'ｒ': {
		class:           classAlphabet,
		order:           18,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'ｓ': {
		class:           classAlphabet,
		order:           19,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'ｔ': {
		class:           classAlphabet,
		order:           20,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'ｕ': {
		class:           classAlphabet,
		order:           21,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'ｖ': {
		class:           classAlphabet,
		order:           22,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'ｗ': {
		class:           classAlphabet,
		order:           23,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'ｘ': {
		class:           classAlphabet,
		order:           24,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'ｙ': {
		class:           classAlphabet,
		order:           25,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'ｚ': {
		class:           classAlphabet,
		order:           26,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'a': {
		class:           classAlphabet,
		order:           1,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'b': {
		class:           classAlphabet,
		order:           2,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'c': {
		class:           classAlphabet,
		order:           3,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'd': {
		class:           classAlphabet,
		order:           4,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'e': {
		class:           classAlphabet,
		order:           5,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'f': {
		class:           classAlphabet,
		order:           6,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'g': {
		class:           classAlphabet,
		order:           7,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'h': {
		class:           classAlphabet,
		order:           8,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'i': {
		class:           classAlphabet,
		order:           9,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'j': {
		class:           classAlphabet,
		order:           10,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'k': {
		class:           classAlphabet,
		order:           11,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'l': {
		class:           classAlphabet,
		order:           12,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'm': {
		class:           classAlphabet,
		order:           13,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'n': {
		class:           classAlphabet,
		order:           14,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'o': {
		class:           classAlphabet,
		order:           15,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'p': {
		class:           classAlphabet,
		order:           16,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'q': {
		class:           classAlphabet,
		order:           17,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'r': {
		class:           classAlphabet,
		order:           18,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	's': {
		class:           classAlphabet,
		order:           19,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	't': {
		class:           classAlphabet,
		order:           20,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'u': {
		class:           classAlphabet,
		order:           21,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'v': {
		class:           classAlphabet,
		order:           22,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'w': {
		class:           classAlphabet,
		order:           23,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'x': {
		class:           classAlphabet,
		order:           24,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'y': {
		class:           classAlphabet,
		order:           25,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},
	'z': {
		class:           classAlphabet,
		order:           26,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseLower,
	},

	'ā': {
		class:           classAlphabet,
		order:           1,
		diacriticalMark: diacriticalMarkMacron,
		letterCase:      letterCaseLower,
	},
	'ī': {
		class:           classAlphabet,
		order:           9,
		diacriticalMark: diacriticalMarkMacron,
		letterCase:      letterCaseLower,
	},
	'ū': {
		class:           classAlphabet,
		order:           21,
		diacriticalMark: diacriticalMarkMacron,
		letterCase:      letterCaseLower,
	},
	'ē': {
		class:           classAlphabet,
		order:           5,
		diacriticalMark: diacriticalMarkMacron,
		letterCase:      letterCaseLower,
	},
	'ō': {
		class:           classAlphabet,
		order:           15,
		diacriticalMark: diacriticalMarkMacron,
		letterCase:      letterCaseLower,
	},

	'â': {
		class:           classAlphabet,
		order:           1,
		diacriticalMark: diacriticalMarkCircumflexAccent,
		letterCase:      letterCaseLower,
	},
	'î': {
		class:           classAlphabet,
		order:           9,
		diacriticalMark: diacriticalMarkCircumflexAccent,
		letterCase:      letterCaseLower,
	},
	'û': {
		class:           classAlphabet,
		order:           21,
		diacriticalMark: diacriticalMarkCircumflexAccent,
		letterCase:      letterCaseLower,
	},
	'ê': {
		class:           classAlphabet,
		order:           5,
		diacriticalMark: diacriticalMarkCircumflexAccent,
		letterCase:      letterCaseLower,
	},
	'ô': {
		class:           classAlphabet,
		order:           15,
		diacriticalMark: diacriticalMarkCircumflexAccent,
		letterCase:      letterCaseLower,
	},

	'Ａ': {
		class:           classAlphabet,
		order:           1,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'Ｂ': {
		class:           classAlphabet,
		order:           2,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'Ｃ': {
		class:           classAlphabet,
		order:           3,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'Ｄ': {
		class:           classAlphabet,
		order:           4,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'Ｅ': {
		class:           classAlphabet,
		order:           5,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'Ｆ': {
		class:           classAlphabet,
		order:           6,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'Ｇ': {
		class:           classAlphabet,
		order:           7,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'Ｈ': {
		class:           classAlphabet,
		order:           8,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'Ｉ': {
		class:           classAlphabet,
		order:           9,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'Ｊ': {
		class:           classAlphabet,
		order:           10,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'Ｋ': {
		class:           classAlphabet,
		order:           11,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'Ｌ': {
		class:           classAlphabet,
		order:           12,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'Ｍ': {
		class:           classAlphabet,
		order:           13,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'Ｎ': {
		class:           classAlphabet,
		order:           14,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'Ｏ': {
		class:           classAlphabet,
		order:           15,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'Ｐ': {
		class:           classAlphabet,
		order:           16,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'Ｑ': {
		class:           classAlphabet,
		order:           17,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'Ｒ': {
		class:           classAlphabet,
		order:           18,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'Ｓ': {
		class:           classAlphabet,
		order:           19,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'Ｔ': {
		class:           classAlphabet,
		order:           20,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'Ｕ': {
		class:           classAlphabet,
		order:           21,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'Ｖ': {
		class:           classAlphabet,
		order:           22,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'Ｗ': {
		class:           classAlphabet,
		order:           23,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'Ｘ': {
		class:           classAlphabet,
		order:           24,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'Ｙ': {
		class:           classAlphabet,
		order:           25,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'Ｚ': {
		class:           classAlphabet,
		order:           26,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'A': {
		class:           classAlphabet,
		order:           1,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'B': {
		class:           classAlphabet,
		order:           2,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'C': {
		class:           classAlphabet,
		order:           3,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'D': {
		class:           classAlphabet,
		order:           4,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'E': {
		class:           classAlphabet,
		order:           5,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'F': {
		class:           classAlphabet,
		order:           6,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'G': {
		class:           classAlphabet,
		order:           7,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'H': {
		class:           classAlphabet,
		order:           8,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'I': {
		class:           classAlphabet,
		order:           9,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'J': {
		class:           classAlphabet,
		order:           10,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'K': {
		class:           classAlphabet,
		order:           11,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'L': {
		class:           classAlphabet,
		order:           12,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'M': {
		class:           classAlphabet,
		order:           13,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'N': {
		class:           classAlphabet,
		order:           14,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'O': {
		class:           classAlphabet,
		order:           15,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'P': {
		class:           classAlphabet,
		order:           16,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'Q': {
		class:           classAlphabet,
		order:           17,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'R': {
		class:           classAlphabet,
		order:           18,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'S': {
		class:           classAlphabet,
		order:           19,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'T': {
		class:           classAlphabet,
		order:           20,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'U': {
		class:           classAlphabet,
		order:           21,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'V': {
		class:           classAlphabet,
		order:           22,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'W': {
		class:           classAlphabet,
		order:           23,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'X': {
		class:           classAlphabet,
		order:           24,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'Y': {
		class:           classAlphabet,
		order:           25,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},
	'Z': {
		class:           classAlphabet,
		order:           26,
		diacriticalMark: diacriticalMarkNone,
		letterCase:      letterCaseUpper,
	},

	'Ā': {
		class:           classAlphabet,
		order:           1,
		diacriticalMark: diacriticalMarkMacron,
		letterCase:      letterCaseUpper,
	},
	'Ī': {
		class:           classAlphabet,
		order:           9,
		diacriticalMark: diacriticalMarkMacron,
		letterCase:      letterCaseUpper,
	},
	'Ū': {
		class:           classAlphabet,
		order:           21,
		diacriticalMark: diacriticalMarkMacron,
		letterCase:      letterCaseUpper,
	},
	'Ē': {
		class:           classAlphabet,
		order:           5,
		diacriticalMark: diacriticalMarkMacron,
		letterCase:      letterCaseUpper,
	},
	'Ō': {
		class:           classAlphabet,
		order:           15,
		diacriticalMark: diacriticalMarkMacron,
		letterCase:      letterCaseUpper,
	},

	'Â': {
		class:           classAlphabet,
		order:           1,
		diacriticalMark: diacriticalMarkCircumflexAccent,
		letterCase:      letterCaseUpper,
	},
	'Î': {
		class:           classAlphabet,
		order:           9,
		diacriticalMark: diacriticalMarkCircumflexAccent,
		letterCase:      letterCaseUpper,
	},
	'Û': {
		class:           classAlphabet,
		order:           21,
		diacriticalMark: diacriticalMarkCircumflexAccent,
		letterCase:      letterCaseUpper,
	},
	'Ê': {
		class:           classAlphabet,
		order:           5,
		diacriticalMark: diacriticalMarkCircumflexAccent,
		letterCase:      letterCaseUpper,
	},
	'Ô': {
		class:           classAlphabet,
		order:           15,
		diacriticalMark: diacriticalMarkCircumflexAccent,
		letterCase:      letterCaseUpper,
	},

	// 仮名
	'あ': {
		class:      classKana,
		order:      1,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'い': {
		class:      classKana,
		order:      2,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'う': {
		class:      classKana,
		order:      3,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'え': {
		class:      classKana,
		order:      4,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'お': {
		class:      classKana,
		order:      5,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'か': {
		class:      classKana,
		order:      6,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'き': {
		class:      classKana,
		order:      7,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'く': {
		class:      classKana,
		order:      8,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'け': {
		class:      classKana,
		order:      9,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'こ': {
		class:      classKana,
		order:      10,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'さ': {
		class:      classKana,
		order:      11,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'し': {
		class:      classKana,
		order:      12,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'す': {
		class:      classKana,
		order:      13,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'せ': {
		class:      classKana,
		order:      14,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'そ': {
		class:      classKana,
		order:      15,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'た': {
		class:      classKana,
		order:      16,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'ち': {
		class:      classKana,
		order:      17,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'つ': {
		class:      classKana,
		order:      18,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'て': {
		class:      classKana,
		order:      19,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'と': {
		class:      classKana,
		order:      20,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'な': {
		class:      classKana,
		order:      21,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'に': {
		class:      classKana,
		order:      22,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'ぬ': {
		class:      classKana,
		order:      23,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'ね': {
		class:      classKana,
		order:      24,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'の': {
		class:      classKana,
		order:      25,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'は': {
		class:      classKana,
		order:      26,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'ひ': {
		class:      classKana,
		order:      27,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'ふ': {
		class:      classKana,
		order:      28,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'へ': {
		class:      classKana,
		order:      29,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'ほ': {
		class:      classKana,
		order:      30,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'ま': {
		class:      classKana,
		order:      31,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'み': {
		class:      classKana,
		order:      32,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'む': {
		class:      classKana,
		order:      33,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'め': {
		class:      classKana,
		order:      34,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'も': {
		class:      classKana,
		order:      35,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'や': {
		class:      classKana,
		order:      36,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'ゆ': {
		class:      classKana,
		order:      37,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'よ': {
		class:      classKana,
		order:      38,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'ら': {
		class:      classKana,
		order:      39,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'り': {
		class:      classKana,
		order:      40,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'る': {
		class:      classKana,
		order:      41,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'れ': {
		class:      classKana,
		order:      42,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'ろ': {
		class:      classKana,
		order:      42,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'わ': {
		class:      classKana,
		order:      44,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'ゐ': {
		class:      classKana,
		order:      45,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'ゑ': {
		class:      classKana,
		order:      46,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'を': {
		class:      classKana,
		order:      47,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'ん': {
		class:      classKana,
		order:      48,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},

	'が': {
		class:      classKana,
		order:      6,
		voiced:     voicedVoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'ぎ': {
		class:      classKana,
		order:      7,
		voiced:     voicedVoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'ぐ': {
		class:      classKana,
		order:      8,
		voiced:     voicedVoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'げ': {
		class:      classKana,
		order:      9,
		voiced:     voicedVoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'ご': {
		class:      classKana,
		order:      10,
		voiced:     voicedVoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'ざ': {
		class:      classKana,
		order:      11,
		voiced:     voicedVoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'じ': {
		class:      classKana,
		order:      12,
		voiced:     voicedVoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'ず': {
		class:      classKana,
		order:      13,
		voiced:     voicedVoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'ぜ': {
		class:      classKana,
		order:      14,
		voiced:     voicedVoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'ぞ': {
		class:      classKana,
		order:      15,
		voiced:     voicedVoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'だ': {
		class:      classKana,
		order:      16,
		voiced:     voicedVoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'ぢ': {
		class:      classKana,
		order:      17,
		voiced:     voicedVoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'づ': {
		class:      classKana,
		order:      18,
		voiced:     voicedVoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'で': {
		class:      classKana,
		order:      19,
		voiced:     voicedVoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'ど': {
		class:      classKana,
		order:      20,
		voiced:     voicedVoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'ば': {
		class:      classKana,
		order:      26,
		voiced:     voicedVoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'び': {
		class:      classKana,
		order:      27,
		voiced:     voicedVoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'ぶ': {
		class:      classKana,
		order:      28,
		voiced:     voicedVoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'べ': {
		class:      classKana,
		order:      29,
		voiced:     voicedVoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'ぼ': {
		class:      classKana,
		order:      30,
		voiced:     voicedVoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},

	'ぱ': {
		class:      classKana,
		order:      26,
		voiced:     voicedSemivoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'ぴ': {
		class:      classKana,
		order:      27,
		voiced:     voicedSemivoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'ぷ': {
		class:      classKana,
		order:      28,
		voiced:     voicedSemivoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'ぺ': {
		class:      classKana,
		order:      29,
		voiced:     voicedSemivoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},
	'ぽ': {
		class:      classKana,
		order:      30,
		voiced:     voicedSemivoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeHigagana,
	},

	'ぁ': {
		class:      classKana,
		order:      1,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeLower,
		kanaType:   kanaTypeHigagana,
	},
	'ぃ': {
		class:      classKana,
		order:      2,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeLower,
		kanaType:   kanaTypeHigagana,
	},
	'ぅ': {
		class:      classKana,
		order:      3,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeLower,
		kanaType:   kanaTypeHigagana,
	},
	'ぇ': {
		class:      classKana,
		order:      4,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeLower,
		kanaType:   kanaTypeHigagana,
	},
	'ぉ': {
		class:      classKana,
		order:      5,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeLower,
		kanaType:   kanaTypeHigagana,
	},
	'っ': {
		class:      classKana,
		order:      18,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeLower,
		kanaType:   kanaTypeHigagana,
	},
	'ゃ': {
		class:      classKana,
		order:      36,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeLower,
		kanaType:   kanaTypeHigagana,
	},
	'ゅ': {
		class:      classKana,
		order:      37,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeLower,
		kanaType:   kanaTypeHigagana,
	},
	'ょ': {
		class:      classKana,
		order:      38,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeLower,
		kanaType:   kanaTypeHigagana,
	},
	'ゎ': {
		class:      classKana,
		order:      44,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeLower,
		kanaType:   kanaTypeHigagana,
	},

	'ゝ': {
		class:      classKana,
		order:      49,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeRepeat,
		kanaType:   kanaTypeHigagana,
	},
	'ゞ': {
		class:      classKana,
		order:      49,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeRepeat,
		kanaType:   kanaTypeHigagana,
	},

	'ア': {
		class:      classKana,
		order:      1,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'イ': {
		class:      classKana,
		order:      2,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ウ': {
		class:      classKana,
		order:      3,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'エ': {
		class:      classKana,
		order:      4,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'オ': {
		class:      classKana,
		order:      5,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'カ': {
		class:      classKana,
		order:      6,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'キ': {
		class:      classKana,
		order:      7,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ク': {
		class:      classKana,
		order:      8,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ケ': {
		class:      classKana,
		order:      9,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'コ': {
		class:      classKana,
		order:      10,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'サ': {
		class:      classKana,
		order:      11,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'シ': {
		class:      classKana,
		order:      12,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ス': {
		class:      classKana,
		order:      13,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'セ': {
		class:      classKana,
		order:      14,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ソ': {
		class:      classKana,
		order:      15,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'タ': {
		class:      classKana,
		order:      16,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'チ': {
		class:      classKana,
		order:      17,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ツ': {
		class:      classKana,
		order:      18,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'テ': {
		class:      classKana,
		order:      19,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ト': {
		class:      classKana,
		order:      20,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ナ': {
		class:      classKana,
		order:      21,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ニ': {
		class:      classKana,
		order:      22,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ヌ': {
		class:      classKana,
		order:      23,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ネ': {
		class:      classKana,
		order:      24,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ノ': {
		class:      classKana,
		order:      25,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ハ': {
		class:      classKana,
		order:      26,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ヒ': {
		class:      classKana,
		order:      27,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'フ': {
		class:      classKana,
		order:      28,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ヘ': {
		class:      classKana,
		order:      29,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ホ': {
		class:      classKana,
		order:      30,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'マ': {
		class:      classKana,
		order:      31,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ミ': {
		class:      classKana,
		order:      32,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ム': {
		class:      classKana,
		order:      33,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'メ': {
		class:      classKana,
		order:      34,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'モ': {
		class:      classKana,
		order:      35,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ヤ': {
		class:      classKana,
		order:      36,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ユ': {
		class:      classKana,
		order:      37,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ヨ': {
		class:      classKana,
		order:      38,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ラ': {
		class:      classKana,
		order:      39,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'リ': {
		class:      classKana,
		order:      40,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ル': {
		class:      classKana,
		order:      41,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'レ': {
		class:      classKana,
		order:      42,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ロ': {
		class:      classKana,
		order:      43,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ワ': {
		class:      classKana,
		order:      44,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ヰ': {
		class:      classKana,
		order:      45,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ヱ': {
		class:      classKana,
		order:      46,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ヲ': {
		class:      classKana,
		order:      47,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ン': {
		class:      classKana,
		order:      48,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},

	'ヴ': {
		class:      classKana,
		order:      3,
		voiced:     voicedVoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ガ': {
		class:      classKana,
		order:      6,
		voiced:     voicedVoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ギ': {
		class:      classKana,
		order:      7,
		voiced:     voicedVoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'グ': {
		class:      classKana,
		order:      8,
		voiced:     voicedVoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ゲ': {
		class:      classKana,
		order:      9,
		voiced:     voicedVoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ゴ': {
		class:      classKana,
		order:      10,
		voiced:     voicedVoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ザ': {
		class:      classKana,
		order:      11,
		voiced:     voicedVoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ジ': {
		class:      classKana,
		order:      12,
		voiced:     voicedVoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ズ': {
		class:      classKana,
		order:      13,
		voiced:     voicedVoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ゼ': {
		class:      classKana,
		order:      14,
		voiced:     voicedVoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ゾ': {
		class:      classKana,
		order:      15,
		voiced:     voicedVoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ダ': {
		class:      classKana,
		order:      16,
		voiced:     voicedVoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ヂ': {
		class:      classKana,
		order:      17,
		voiced:     voicedVoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ヅ': {
		class:      classKana,
		order:      18,
		voiced:     voicedVoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'デ': {
		class:      classKana,
		order:      19,
		voiced:     voicedVoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ド': {
		class:      classKana,
		order:      20,
		voiced:     voicedVoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'バ': {
		class:      classKana,
		order:      26,
		voiced:     voicedVoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ビ': {
		class:      classKana,
		order:      27,
		voiced:     voicedVoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ブ': {
		class:      classKana,
		order:      28,
		voiced:     voicedVoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ベ': {
		class:      classKana,
		order:      29,
		voiced:     voicedVoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ボ': {
		class:      classKana,
		order:      30,
		voiced:     voicedVoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},

	'パ': {
		class:      classKana,
		order:      26,
		voiced:     voicedSemivoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ピ': {
		class:      classKana,
		order:      27,
		voiced:     voicedSemivoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'プ': {
		class:      classKana,
		order:      28,
		voiced:     voicedSemivoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ペ': {
		class:      classKana,
		order:      29,
		voiced:     voicedSemivoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},
	'ポ': {
		class:      classKana,
		order:      30,
		voiced:     voicedSemivoiced,
		symbolType: symbolTypeUpper,
		kanaType:   kanaTypeKatakana,
	},

	'ァ': {
		class:      classKana,
		order:      1,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeLower,
		kanaType:   kanaTypeKatakana,
	},
	'ィ': {
		class:      classKana,
		order:      2,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeLower,
		kanaType:   kanaTypeKatakana,
	},
	'ゥ': {
		class:      classKana,
		order:      3,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeLower,
		kanaType:   kanaTypeKatakana,
	},
	'ェ': {
		class:      classKana,
		order:      4,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeLower,
		kanaType:   kanaTypeKatakana,
	},
	'ォ': {
		class:      classKana,
		order:      5,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeLower,
		kanaType:   kanaTypeKatakana,
	},
	'ッ': {
		class:      classKana,
		order:      18,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeLower,
		kanaType:   kanaTypeKatakana,
	},
	'ャ': {
		class:      classKana,
		order:      36,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeLower,
		kanaType:   kanaTypeKatakana,
	},
	'ュ': {
		class:      classKana,
		order:      37,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeLower,
		kanaType:   kanaTypeKatakana,
	},
	'ョ': {
		class:      classKana,
		order:      38,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeLower,
		kanaType:   kanaTypeKatakana,
	},
	'ヮ': {
		class:      classKana,
		order:      44,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeLower,
		kanaType:   kanaTypeKatakana,
	},

	'ヽ': {
		class:      classKana,
		order:      49,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeRepeat,
		kanaType:   kanaTypeKatakana,
	},
	'ヾ': {
		class:      classKana,
		order:      49,
		voiced:     voicedVoiced,
		symbolType: symbolTypeRepeat,
		kanaType:   kanaTypeKatakana,
	},

	'ー': {
		class:      classKana,
		order:      50,
		voiced:     voicedUnvoiced,
		symbolType: symbolTypeLongVowel,
		kanaType:   kanaTypeKatakana,
	},
}
